version: '3.7'
services:
    php:
        container_name: hired-php
        env_file:
          - api/.env
        build: docker/php
        volumes:
          - ./api:/var/www/symfony:cached
        ports:
          - 9000:9001
        links:
          - db
    nginx:
        container_name: hired-nginx
        env_file:
          - api/.env
        build: docker/nginx
        ports:
          - ${HTTP_PORT_HOST:-80}:80
        links:
          - php
        volumes:
          - ./api:/var/www/symfony:ro
    db:
        container_name: hired-database
        env_file:
          - api/.env
        image: postgres:11.2
        volumes:
          - ./postgres-data:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: symfony
            POSTGRES_DB: symfony
            POSTGRES_USER: symfony
