version: '3.7'
services:
    php:
        container_name: hired-php
        build: docker/php
        volumes:
          - ./:/var/www/symfony:cached
        ports:
          - 9000:9001
        links:
          - db
    nginx:
        container_name: hired-nginx
        build: docker/nginx
        ports:
          - ${HTTP_PORT_HOST:-80}:80
        links:
          - php
        volumes:
          - ./:/var/www/symfony:ro
    db:
        container_name: hired-database
        image: postgres:11.2
        volumes:
          - ./postgres-data:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: symfony
            POSTGRES_DB: symfony
            POSTGRES_USER: symfony
    node:
        build: docker/node
        working_dir: /var/www/symfony
        links:
          - php
        depends_on:
          - php
        volumes:
          - ./:/var/www/symfony
        environment:
            NODE_ENV: development
